language: node_js
node_js:
- '5'
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_19134462ce56_key -iv $encrypted_19134462ce56_iv
  -in ecs-task.json.enc -out ecs-task.json -d
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- npm test
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.bash"
env:
  global:
  - secure: qN9ekS8xOcisUm4Cu9ICCEMmhVAyycJWATJVwtrE/eEJSCz4ljNaharwdHY52k+Y6jXxPt1u+XI7n1YtpvEKIpUu1CVUxjSslZQ0IfJM9VnMfNjx7Lv8nknHI9tJADTB5ZgpsVoxtNHy+7bkAiAcL/Brut6sc0e0mdBFOxi03uSKiNeNDHF+Z0fI3AXzbHMP39PLhM32AYouTGg47Xw5XRCpyrVulEj+JWVJOml0MWJc6dBu1Kq5xrjEhNYm5+kgGSthiLNJmZ3sWgdaPXmsDwhMIAmfZ1MhKqFLRINQ7VaJRbE2y2culJB8D040thz25hoZg0MUq/aL16QHt3rd4RmIjTeaBN3zw2+9zvfuDHQzwuQMZe6oz1vbGBvWwis3CNy1StjQ2TnmaPQMSOjHZFwx33MpWo72t1qvwgmOPbEyeEeNE25dcf4VIkr+mj6Dr8o+MaOgIPd3u2FjlUAWsAbv/j4jc09FiMOh7HMuEByXviyF34MUq+3WoRrMnKQBeuUqyYsNgsnXbrL2hJfkYFy9lOVvoHg5z12EciIdT/NcxeN12IK8RuzfeD+OQcYOHV1wy4z6UTo/NWBh5lX0LPieO4Rx3baBPi9sR1eRNq8TPFQvam5uu5HwERBQUGBhgFTZQyKcBYtnQaSvV2wjaQPUCGZJFw6tCEZCRpYZHKU=
  - secure: id7ABmVoU3As2S30Jtx/8N5664uuJSUJ4wjzMrMY6cwavxNj5ySa1ZZNZJqSyQEPVrR9USxSX0Fn7eI7eTGkpkVrCtVE6LrUfNwxMuXmpMmJeaDOp6mcaA7Y43CgRL6TusQy2pajL5vaENG7all/abVZeixNq/dFjqDcg0gEHwZi+3oqpPl+V+JgEF2C+7gzz4qN82g1vLzc6Zn//Pd/1ctFRXVwn8Kxn2R3gywEruRlf2gERNl7AwC8QwddHnF+LZYGSJsAl2Iibi/KcN4wroTe6UJIgR+//nFyV8ikJz9tSuhFH2ItDo0ELC+lt8pT2BEhasBIUdUW6vexuRaa9j9x6IgtqksCnE9asohmTUsmtsws6YJWW6xdojcSE9oFSmZTH9ZkRepu56WiJwTpp27waJbCXun//EVpJo4cyacG8dF0xO/8GqL4/krHzprMxq2l5675oGrLUq0KdE82PGk7cJ0jx22Vkfew4Po1FJ33xyMf3kxbzYnP4w5k/G4/LGDYszXhlnuLQWPaBQ9H/OZ8+twR0skygdygoe//1InvitGUes/27G4hExLg+D04Xtd+k7Qi9jKLurpqcZJsMmr8RZck0GG5vLxNeOvY56t6pn8GTCPJwGV1nvY/poqEPud2cyKPn4XoN4unqZYxBgUyBIYzBi+T47XKXk0TIuc=
