language: node_js
node_js:
- '5'
before_install:
- openssl aes-256-cbc -K $encrypted_19134462ce56_key -iv $encrypted_19134462ce56_iv
  -in ecs-task.json.enc -out ecs-task.json -d
deploy:
  provider: script
  script: ./deploy.bash
