language: node_js
node_js:
- '5'
before_install:
- openssl aes-256-cbc -K $encrypted_19134462ce56_key -iv $encrypted_19134462ce56_iv
  -in ecs-task.json.enc -out ecs-task.json -d
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.bash"
env:
  global:
  - secure: eLjexBG86C84f7vIFtq5d/ccszhVYqQ5ZaW8AbF4uRObIEwEGpAQhgvp9gGUkeNjt+lkVnssmPaOflIz9wbRWPlRsVGsi64cRwsrbp69irvfzsbxE+wb2TkQEx57FjKNqk4AyMAwD1n4HxTvvaUbfkAIOg2COuQYXNp/zygP8jUOwVWjM2zOkO/kgz4WXinhcYF7E3bUSwEQ63aypKdYzz7fQkge95XOIJtV30YXeD2p4k7vBXnIAeS02Wfbi24rZkkx4xNdFwbNnD8N8IyxwsVb4f9KqjL/ZZT+QqdMxGvPnsTaOnCPo+XkXZ2O15GgpN0Y15K6zWTCG2oY4r96tO6nM9O267jo10YvrejpT8tXC0W4cXKLRnntpN+qGZE6i8BPVsnrnxjwnJqxJcPoW8n5gLiZKoznfmLobhUWAUaNEIz5Mcz8+tyRjeQ0EqZv5Jn69lfFaN/Q7d1fnhvVfkgTWJ6UWyaRAbZH2y1I0UoF5nsvGMa1RkRLIoDLEP/pXQpr/2qWvg4qhaODFXBEj0SQaq9cQz3rf8wrlhT/tlUQEWxo2SlgZncWpVNghcWoRsTk9V3Y2BJ9bbKV99djY5lsrY7j6rvV+0kF4lfhg/g6W1LnwuvCJlcgBSAJSf6mSk7uKek7uf5OIxdLnXNw4dcDZZt3r/oxfuojlKl0TYQ=
